name: 'Deploy RyunixJS to GitHub Pages'
description: 'Build and deploy ryunixjs to GitHub pages'
outputs:
  page_url:
    description: "page url"
    value: ${{ steps.deploy.outputs.page_url }}

runs:
  using: 'composite'

  steps:
    - name: Setup Node
      uses: actions/setup-node@v3.8.1
      with:
        node-version: "18"

    - name: 'Build'
      shell: bash
      run: |
        npm install
        npm ci
        npm run build

    - name: 'upload'
      uses: actions/upload-pages-artifact@v1.0.4
      with: 
        path: ${{ inputs.path }}

    - id: deploy
      name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v1
      with:
        token: ${{ github.token }}
