name: 'Deploy RyunixJS to GitHub Pages'
description: 'Build and deploy ryunixjs to GitHub pages'

inputs:
  path:
    description: 'Build directory'
    required: false
    default: '.ryunix'
    
outputs:
  page_url:
    description: "page url"
    value: ${{ steps.deploy.outputs.page_url }}

runs:
  using: 'composite'

  steps:
    - name: Download files from the current repository
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: "18"
    - name: 'Build'
      shell: bash
      run: |
        npm install
        npm ci
        npm run build

    - name: 'upload'
      uses: actions/upload-pages-artifact@v1.0.4
      with: 
        path: ${{ inputs.path }}

    - id: deploy
      name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v1
      with:
        token: ${{ github.token }}
